name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install pytest flake8 black

      - name: Ejecutar tests
        run: pytest -v
        env:
          PYTHONPATH: .

      - name: Ejecutar flake8
        run: flake8 .

      - name: Verificar formato con black
        run: black --check .

  publish:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Clonar repo
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker build -t agustin4/repo-uno:latest .

      - name: Push image
        run: docker push agustin4/repo-uno:latest

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v4

      - name: Build imagen Docker
        run: docker build -t repo-uno .